### ISSUE TITLE
Bad performance with large options array

### ISSUE THREAD

**Issue by indesignlatam** [robcalcroft/react-native-multiselect#1]
Hi, 

I just tried this package with a large set of options and the performance when you click on one option is very bad, the checkmark appears after several seconds.

I think this can be solved by creating a separate component for the rows and implement shouldComponentUpdate.

Ill try that and make a pull request if it works.

**Comment by robcalcroft** [comment]
Hey! Thanks for spotting this I've only used this on a small project so thanks for catching this. Haven't done a lot of work on it so any improvements are very welcomed! 😊

**Comment by indesignlatam** [comment]
Thanks to you for open sourcing this project

**Comment by robcalcroft** [comment]
No problem at all glad its' been of use to you. I look forward to your PR 😄

**Comment by robcalcroft** [comment]
ff2ca531dc78be317de9e7de72bd3976f7785839 / `2.0.0` should be sorted 👍

**Comment by indesignlatam** [comment]
Sorry I didn't worked on this, I got work on another project and had no time to look in to this.

Thanks man.

**Comment by robcalcroft** [comment]
No problem 😄
